{% set name = "pytorchvideo" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorchvideo-{{ version }}.tar.gz
  sha256: 69a3424c7feb70422da59d0cec17b56657984bd0ba8d5d78cad08a328cf6341b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fvcore
    - av
    - parameterized
    - iopath
    - networkx

test:
  imports:
    - pytorchvideo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facebookresearch/pytorchvideo
  summary: A video understanding deep learning library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
